function [fitresult, gof] = createFit(tttt, F)
%CREATEFIT(TTTT,F)
%  Create a fit.
%
%  Data for 'equation' fit:
%      X Input : tttt
%      Y Output: F
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Nov-2019 16:57:47


%% Fit: 'equation'.
[xData, yData] = prepareCurveData( tttt, F );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'equation' );
h = plot( fitresult, xData, yData );
legend( h, 'F vs. tttt', 'equation', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'tttt', 'Interpreter', 'none' );
ylabel( 'F', 'Interpreter', 'none' );
grid on


